### ISSUE TITLE
.changelogrc specification

### ISSUE THREAD

**Issue by rafinskipg** [rafinskipg/git-changelog#31]
Hi @JohnnyEstilles , 

I have started working on the .changelogrc specification for the version 0.2.0 , but previously i'm doing some refactors, i have started with the logger and i will continue this week. 

I would like you to take a look to the specification and let me know if you have any thought about it : https://github.com/rafinskipg/git-changelog/tree/changelogrc#changelogrc-specification

Also i will create a issue with the things needed for 0.2.0

Thanks

**Comment by rafinskipg** [comment]
See #32 for v0.2.0 Goals, add any suggestion you want :)

**Comment by JohnnyEstilles** [comment]
@rafinskipg ... That's awesome! Since you already started on `v0.2.0` I will hold off on the transition to `Bluebird` (#22). I fear simultaneous work on these two will yield a large number of conflicts. We can either do it as the last step to `0.2.0` or on the next release. You're call. The `Bluebird` transition will be a non-breaking change, so we can do it any time.

**Comment by JohnnyEstilles** [comment]
I'll check out the new specifications and goals and comment on them a bit later during the day.

**Comment by rafinskipg** [comment]
I have updated all the README with more changes https://github.com/rafinskipg/git-changelog/blob/changelogrc/README.md  :+1:
